version: '3.8'
services:
    app:
        container_name: ${DOCKER_IMAGE}-container
        ports:
            - '${API_PORT}:${API_PORT}'
        build:
            context: .
            args:
                - PROJECT=${PROJECT}
            dockerfile: Dockerfile
        image: ${DOCKER_IMAGE}
        volumes:
            - .:/_projects/${PROJECT}
        command: bun run dev
        init: true
        ulimits:
            memlock: -1
