version: '3.8'
services:
    app:
        container_name: ${DOCKER_IMAGE}-container
        privileged: true
        ports:
            - '${API_PORT}:${API_PORT}'
        build:
            context: .
            args:
                - PROJECT=${PROJECT}
            dockerfile: Dockerfile
        image: ${DOCKER_IMAGE}
        volumes:
            - .:/_projects/${PROJECT}
        command: ["sh", "-c", "bun i && bun run dev"]
        restart: always
        init: true
        ulimits:
            memlock: -1
        tty: true
